replicaCount: 2

image:
  repository: ""
  tag: latest
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 8080
  headless: false
  annotations: {}
  extraPorts: []
  metrics:
    enabled: false
    port: 9090
    targetPort: 9090

imagePullSecrets: []

serviceAccount:
  create: true
  name: ""
  automount: false
  annotations: {}

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL

configMap:
  enabled: false
  immutable: false
  annotations: {}
  data: {}
  files: {}

secret:
  enabled: false
  type: Opaque
  annotations: {}
  data: {}
  files: {}

hpa:
  enabled: false

readinessProbe:
  enabled: false

livenessProbe:
  enabled: false

startupProbe:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

initContainers: []

global:
  labels: {}