apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cache/redis
- database/postgres-account
- database/postgres-auth
- database/postgres-document
- database/postgres-transaction
- messaging/rabbitmq
- storage/minio
- dev-tools/maildev