apiVersion: v1
kind: Secret
metadata:
  name: transaction-service-secret
  namespace: microbank-dev
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: dHJhbnNhY3Rpb25fZGI=
  SPRING_RABBITMQ_PASSWORD: Z3Vlc3Q=