apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-db-script
data:
{{- $files := .Files.Glob "files/init-scripts/*" }}
{{- range $path, $file := $files }}
  {{ base $path }}: |
{{ $file | indent 4 }}
{{- end }}