apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: microbank
    app.kubernetes.io/managed-by: argocd
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_RABBITMQ_HOST: rabbitmq.rabbitmq.svc.cluster.local
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_MAIL_HOST: maildev.maildev.svc.cluster.local
  SPRING_MAIL_PORT: "1025"
  SENDER_EMAIL: no-reply@microbank.co
  SERVER_PORT: "8085"