apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: microbank
    app.kubernetes.io/managed-by: argocd
type: Opaque
data:
  SPRING_RABBITMQ_PASSWORD: ZGV2cGFzc3dvcmQ=
  SPRING_MAIL_USERNAME: bWFpbGRldg==
  SPRING_MAIL_PASSWORD: bWFpbGRldg==