apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
type: Opaque
data:
  SPRING_RABBITMQ_PASSWORD: ZGV2cGFzc3dvcmQ=
  SPRING_MAIL_USERNAME: bWFpbGRldg==
  SPRING_MAIL_PASSWORD: bWFpbGRldg==