apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform
  sources:
  - repoURL: https://codecentric.github.io/helm-charts
    chart: keycloak                               
    targetRevision: 18.10.0 
    helm:
      releaseName: keycloak
      valueFiles:
        - $values/platform/security/keycloak/values-dev.yaml
  - repoURL: https://github.com/Rajaraman-Ramanathan/microbank-gitops.git
    targetRevision: dev
    ref: values
  destination:
    server: https://microbank-dev-control-plane:6443
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true