apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: <YOUR_GIT_REPO_URL>
    targetRevision: HEAD
    path: platform/shared-infra/storage/minio/helm
    helm:
      releaseName: minio
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true