apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: networking-ingress-dev
  namespace: argocd
  # sync wave annotations configured in such a way that baseline policies are applied before allow policies
spec:
  project: platform
  source:
    repoURL: https://github.com/Rajaraman-Ramanathan/microbank-gitops.git
    targetRevision: dev
    path: platform/bootstrap/networking/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true