apiVersion: v1
kind: Secret
metadata:
  name: account-service-secret
  labels:
    app.kubernetes.io/name: account-service
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: microbank
    app.kubernetes.io/managed-by: argocd
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: YWNjb3VudHBhc3M=