apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: microbank-dev
  labels:
    app: keycloak
spec:
  replicas: 1   # DEV only
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:22.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: keycloak-config
        - secretRef:
            name: keycloak-secret 
        args:
        - start-dev
        - --import-realm
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 10
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 5
        volumeMounts:
        - name: keycloak-realm
          mountPath: /opt/keycloak/data/import
      volumes:
      - name: keycloak-realm
        configMap:
          name: keycloak-realm-config
