postgresql:
  architecture: standalone

  auth:
    username: platformadmin
    password: devpostgrespass
    database: platform

  primary:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        memory: 1Gi
    podLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: microbank
      app.kubernetes.io/managed-by: argocd
      network-role: data
    initdb:
      scriptsConfigMap: postgres-initdb
    containerSecurityContext:
      enabled: true
      runAsNonRoot: true
      allowPrivilegeEscalation: false
    service:
      type: ClusterIP
    networkPolicy:
      enabled: false

  metrics:
    enabled: true