apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: microbank-root-ca
  secretName: root-ca-secret
  duration: 87600h
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer