apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: apigateway-service-circuit-breaker
  namespace: apigateway-service
spec:
  host: apigateway-service.apigateway-service.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 15s
      baseEjectionTime: 30s
      maxEjectionPercent: 30