apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: apigateway-retries
  namespace: apigateway-service
spec:
  hosts:
    - api.microbank.com
  gateways:
    - public-gateway
  http:
  - retries:
      attempts: 3
      perTryTimeout: 3s
      retryOn: gateway-error,connect-failure,refused-stream,5xx
    route:
    - destination:
        host: apigateway-service.apigateway-service.svc.cluster.local