apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-istio
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress