apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny-keycloak.yaml
  - default-deny-minio.yaml
  - default-deny-postgres.yaml
  - default-deny-rabbitmq.yaml
  - default-deny-redis.yaml
  - default-deny-maildev.yaml
  - default-deny-workloads.yaml