apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
{{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      {{- include "microservice.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        {{- include "microservice.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include "microservice.configChecksum" . }}
        checksum/secret: {{ include "microservice.secretChecksum" . }}
        {{- with .Values.podAnnotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "microservice.serviceAccountName" . }}
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{ if .Values.initContainers }}
      initContainers:
      {{ toYaml .Values.initContainers | nindent 8 }}
      {{ end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
        {{ if .Values.configMap.enabled }}
        envFrom:
        {{ if .Values.configMap.enabled }}
        - configMapRef:
        {{- if .Values.checksum.enabled }}
            name: {{ include "microservice.fullname" . }}-{{ include "microservice.configDataChecksum" . | trunc 8 }}
        {{- else }}
            name: {{ include "microservice.fullname" . }}
        {{- end }}
        {{ if .Values.secret.enabled }}
        - secretRef:
            name: {{ include "microservice.fullname" . }}
        {{- end }}
        {{ if .Values.readinessProbe.enabled }}
        readinessProbe:
          {{ toYaml .Values.readinessProbe.config | nindent 10 }}
        {{ end }}
        {{ if .Values.livenessProbe.enabled }}
        livenessProbe:
          {{ toYaml .Values.livenessProbe.config | nindent 10 }}
        {{ end }}
        {{ if .Values.startupProbe.enabled }}
        startupProbe:
          {{ toYaml .Values.startupProbe.config | nindent 10 }}
        {{ end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  {{- include "microservice.selectorLabels" . | nindent 18 }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            {{- include "microservice.selectorLabels" . | nindent 12 }}
      {{ with .Values.nodeSelector }}
      nodeSelector:
      {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.tolerations }}
      tolerations:
      {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.affinity }}
      affinity:
      {{ toYaml . | nindent 8 }}
      {{ end }}