apiVersion: v1
kind: ConfigMap
metadata:
  name: document-service-config
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-document-service:5432/document_db
  SPRING_DATASOURCE_USERNAME: document_db
  MINIO_ENDPOINT: http://minio:9000
  MINIO_BUCKET_NAME: documents
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: guest