apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../platform/networking/ingress/base

patches:
  - target:
      kind: Ingress
      name: keycloak-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: auth.microbank.local