apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: account-service-circuit-breaker
  namespace: account-service
spec:
  host: account-service.account-service.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50