apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  namespace: microbank-dev
type: Opaque
data:
  SPRING_RABBITMQ_USERNAME: Z3Vlc3Q=
  SPRING_RABBITMQ_PASSWORD: Z3Vlc3Q=
  SPRING_MAIL_USERNAME: bWFpbGRldg==
  SPRING_MAIL_PASSWORD: bWFpbGRldg==