apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.14.5
      helm:
        values: |
          installCRDs: true
    - repoURL: https://github.com/Rajaraman-Ramanathan/microbank-gitops.git
      targetRevision: stage
      path: platform/security/cert-manager/base
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true