apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/your-org/platform-gitops
    targetRevision: main
    path: platform/service-mesh/istio/base/helm
    helm:
      valueFiles:
        - values-stage.yaml
  destination:
    name: eks-stage
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=false