apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
  labels:
    app: apigateway-service
spec:
  type: ClusterIP
  selector:
    app: apigateway-service
  ports:
  - name: http
    port: 80    # Keeping port 80 for abstracting the actual port
    targetPort: 8123

