auth:
  adminUser: admin
  existingSecret: keycloak-secret

postgresql:
  enabled: false

externalDatabase:
  enabled: true
  host: postgres-postgresql.postgres.svc.cluster.local
  port: 5432
  user: keycloakuser
  password: keycloakpass
  database: keycloakdb

service:
  type: ClusterIP

replicaCount: 1

image:
  registry: quay.io
  repository: keycloak/keycloak
  tag: 24.0.3

resources:
  requests:
    cpu: 300m
    memory: 512Mi
  limits:
    memory: 1Gi

extraVolumes:
  - name: realm-config
    configMap:
      name: keycloak-realm-config

extraVolumeMounts:
  - name: realm-config
    mountPath: /opt/bitnami/keycloak/data/import

extraStartupArgs: "--import-realm"

extraEnvVarsCM: keycloak-config

metrics:
  enabled: true

networkPolicy:
  enabled: false