apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: document-service-circuit-breaker
  namespace: document-service
spec:
  host: document-service.document-service.svc.cluster.local
  trafficPolicy:
      outlierDetection:
        consecutive5xxErrors: 10
        interval: 30s
        baseEjectionTime: 30s
        maxEjectionPercent: 50