minio:
  mode: standalone

  auth:
    rootUser: devminio
    rootPassword: devminiopassword

  persistence:
    enabled: false

  image:
    tag: latest

  podLabels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: microbank
    app.kubernetes.io/managed-by: argocd
    network-role: platform

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 512Mi

  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    allowPrivilegeEscalation: false

  service:
    type: ClusterIP

  networkPolicy:
    enabled: false

  metrics:
    enabled: true