apiVersion: v1
kind: ConfigMap
metadata:
  name: document-service-config
  labels:
    app.kubernetes.io/name: document-service
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: microbank
    app.kubernetes.io/managed-by: argocd
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-postgresql.postgres.svc.cluster.local:5432/documentdb
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  MINIO_ENDPOINT: http://minio.minio.svc.cluster.local:9000
  MINIO_BUCKET_NAME: transaction-documents
  SPRING_RABBITMQ_HOST: rabbitmq.rabbitmq.svc.cluster.local
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: devuser
  SERVER_PORT: "8084"