apiVersion: v1
kind: Secret
metadata:
  name: document-service-secret
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: ZG9jdW1lbnRwYXNz
  MINIO_ACCESS_KEY: ZGV2bWluaW8=
  MINIO_SECRET_KEY: ZGV2bWluaW9wYXNzd29yZA==
  SPRING_RABBITMQ_PASSWORD: ZGV2cGFzc3dvcmQ=