apiVersion: v1
kind: Secret
metadata:
  name: document-service-secret
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: ZG9jdW1lbnRwYXNz
  MINIO_ACCESS_KEY: Y2FwZWxsYXg=
  MINIO_SECRET_KEY: MTIzNDU2Nzg=
  SPRING_RABBITMQ_PASSWORD: Z3Vlc3Q=