apiVersion: v1
kind: Service
metadata:
  name: document-service
  labels:
    app.kubernetes.io/name: document-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: microbank
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: document-service
  ports:
  - name: http
    port: 80
    targetPort: 8084
