apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: microbank
    app.kubernetes.io/managed-by: argocd
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-postgresql.postgres.svc.cluster.local:5432/authdb
  SPRING_DATASOURCE_USERNAME: authuser
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_DATA_REDIS_HOST: redis-master.redis.svc.cluster.local
  SPRING_DATA_REDIS_PORT: "6379"
  KEYCLOAK_LOGIN_TOKEN_URL: http://auth.microbank.local/realms/microbank/protocol/openid-connect/token
  KEYCLOAK_LOGIN_GRANT_TYPE: password
  KEYCLOAK_LOGIN_CLIENT_ID: microbank-client
  KEYCLOAK_CONFIG_SERVER_URL: http://auth.microbank.local
  KEYCLOAK_CONFIG_REALM: master
  KEYCLOAK_CONFIG_CLIENT_ID: admin-cli
  KEYCLOAK_CONFIG_USERNAME: admin
  SERVER_PORT: "8081"