apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: YXV0aHBhc3M=
  KEYCLOAK_LOGIN_CLIENT_SECRET: b1ZuY0Njb1ZNWkNGUmJpR0E5OXlndkVjc2NsTGN4Vzg=
  KEYCLOAK_CONFIG_PASSWORD: YWRtaW4=
  KEYCLOAK_CONFIG_CLIENT_SECRET: MEUzcUtRd1ZUcWJlcGp6Q2lWZTNWZkc0MUFxTkV0TnU=