apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: microbank
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: authuser
  SPRING_DATASOURCE_PASSWORD: authpass
  KEYCLOAK_LOGIN_CLIENT_SECRET: oVncCcoVMZCFRbiGA99ygvEcsclLcxW8
  KEYCLOAK_CONFIG_PASSWORD: admin123
  KEYCLOAK_CONFIG_CLIENT_SECRET: 0E3qKQwVTqbepjzCiVe3VfG41AqNEtNu