apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: microbank
    app.kubernetes.io/managed-by: argocd
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: YXV0aHBhc3M=
  KEYCLOAK_LOGIN_CLIENT_SECRET: b1ZuY0Njb1ZNWkNGUmJpR0E5OXlndkVjc2NsTGN4Vzg=
  KEYCLOAK_CONFIG_PASSWORD: YWRtaW4xMjM=
  KEYCLOAK_CONFIG_CLIENT_SECRET: MEUzcUtRd1ZUcWJlcGp6Q2lWZTNWZkc0MUFxTkV0TnU=