apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-service-sa
  namespace: account-service
  labels:
    app.kubernetes.io/name: account-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: microbank
    app.kubernetes.io/managed-by: argocd
    tier: workloads
automountServiceAccountToken: true