apiVersion: v1
kind: ServiceAccount
metadata:
  name: apigateway-service-sa
  namespace: apigateway-service
  labels:
    app.kubernetes.io/name: apigateway-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: microbank
    app.kubernetes.io/managed-by: argocd
    tier: workloads
automountServiceAccountToken: true