apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-sa
  namespace: notification-service
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: microbank
    app.kubernetes.io/managed-by: argocd
    tier: workloads
automountServiceAccountToken: true