apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-config
  labels:
    app.kubernetes.io/name: transaction-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: microbank
    app.kubernetes.io/managed-by: argocd
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-postgresql.postgres.svc.cluster.local:5432/transactiondb
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_RABBITMQ_HOST: rabbitmq.rabbitmq.svc.cluster.local
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: devuser
  SERVER_PORT: "8083"