apiVersion: v1
kind: Secret
metadata:
  name: document-service-secret
  namespace: microbank-dev
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: ZG9jdW1lbnRfZGI=
  MINIO_ACCESS_KEY: Y2FwZWxsYXg=
  MINIO_SECRET_KEY: MTIzNDU2Nzg=